name: publish

on:
  release:
    types: [published]     # publish full release to PyPI when a release is created on Github
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish_to_pypi:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
      - run: uv sync
      - run: uv run ruff check --no-fix --select PLE # quick check for syntax errors to avoid waiting time doing the rest of the build
      - run: uv build
      - run: uv run pytest tests                  # dont push the package to PyPI if the tests fail
      - run: uv publish --trusted-publishing always
